name: Deploy Test SSH

on:
  push:
    branches:
      - deploy

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            cd /home/yves/apps/test_ssh

            git pull origin deploy

